/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Glenn
 */
public class adminLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public adminLogin() {
        initComponents();
        
        // Flat Button Design
        adminLoginButton.setBorderPainted(false);
        adminLoginButton.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginLabel1 = new javax.swing.JLabel();
        adminClickHereLabel = new javax.swing.JLabel();
        adminusernameTextField = new javax.swing.JTextField();
        loginLabel3 = new javax.swing.JLabel();
        loginLabel4 = new javax.swing.JLabel();
        loginLabel5 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        adminPasswordField = new javax.swing.JPasswordField();
        adminLoginButton = new javax.swing.JButton();
        adminShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 154, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(361, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        loginLabel.setText("Username");
        jPanel2.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        loginLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 35)); // NOI18N
        loginLabel1.setText("Admin Login");
        jPanel2.add(loginLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        adminClickHereLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        adminClickHereLabel.setForeground(new java.awt.Color(30, 154, 224));
        adminClickHereLabel.setText("Click here");
        adminClickHereLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminClickHereLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminClickHereLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminClickHereLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminClickHereLabelMouseExited(evt);
            }
        });
        jPanel2.add(adminClickHereLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, -1, -1));

        adminusernameTextField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        adminusernameTextField.setPreferredSize(new java.awt.Dimension(490, 42));
        jPanel2.add(adminusernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        loginLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        loginLabel3.setText("Password");
        jPanel2.add(loginLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        loginLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        loginLabel4.setText("Enter your credentials to proceed");
        jPanel2.add(loginLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        loginLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        loginLabel5.setText("Are you an employee?");
        jPanel2.add(loginLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, -1));

        closeButton.setBackground(new java.awt.Color(30, 154, 224));
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 70, -1));

        adminPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        adminPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(adminPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 490, 40));

        adminLoginButton.setBackground(new java.awt.Color(30, 154, 224));
        adminLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginButton.setText("LOGIN NOW");
        adminLoginButton.setBorderPainted(false);
        adminLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(adminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 490, 40));

        adminShowPassword.setText("Showpassword");
        adminShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(adminShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 840, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
       
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        // TODO add your handling code here:
        
        closeButton.setBackground(new java.awt.Color(204,0,51));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        // TODO add your handling code here:
        closeButton.setBackground(new java.awt.Color(30,154,224));
    }//GEN-LAST:event_closeButtonMouseExited

    private void adminPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordFieldActionPerformed

    private void adminClickHereLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminClickHereLabelMouseClicked
        // TODO add your handling code here:
        employeeLogin a = new employeeLogin();
        a.show();
        dispose();
    }//GEN-LAST:event_adminClickHereLabelMouseClicked

    private void adminClickHereLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminClickHereLabelMouseEntered
        adminClickHereLabel.setForeground(new java.awt.Color(172,172,172));
        
    }//GEN-LAST:event_adminClickHereLabelMouseEntered

    private void adminClickHereLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminClickHereLabelMouseExited
        adminClickHereLabel.setForeground(new java.awt.Color(30,154,224));
    }//GEN-LAST:event_adminClickHereLabelMouseExited

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void adminShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminShowPasswordActionPerformed
        if (adminShowPassword.isSelected()){
            adminPasswordField.setEchoChar((char)0);
        }else{
            adminPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_adminShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminClickHereLabel;
    public javax.swing.JButton adminLoginButton;
    private javax.swing.JPasswordField adminPasswordField;
    private javax.swing.JCheckBox adminShowPassword;
    private javax.swing.JTextField adminusernameTextField;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JLabel loginLabel3;
    private javax.swing.JLabel loginLabel4;
    private javax.swing.JLabel loginLabel5;
    // End of variables declaration//GEN-END:variables
}
