/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;

/**
 *
 * @author Glenn
 */
public class employeeLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public employeeLogin() {
        initComponents();
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPannel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        employeeclickhereLabel = new javax.swing.JLabel();
        employeeusernameTextField = new javax.swing.JTextField();
        adminpasswordLabel = new javax.swing.JLabel();
        loginLabel4 = new javax.swing.JLabel();
        switchLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        employeePasswordField = new javax.swing.JPasswordField();
        adminLoginButton = new javax.swing.JButton();
        employeeShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPannel.setBackground(new java.awt.Color(30, 154, 224));
        leftPannel.setPreferredSize(new java.awt.Dimension(361, 700));
        leftPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(leftPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        usernameLabel.setText("Username");
        rightPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        loginLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 35)); // NOI18N
        loginLabel.setText("Employee Login");
        rightPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        employeeclickhereLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        employeeclickhereLabel.setForeground(new java.awt.Color(30, 154, 224));
        employeeclickhereLabel.setText("Click here");
        employeeclickhereLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeclickhereLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeclickhereLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeclickhereLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeclickhereLabelMouseExited(evt);
            }
        });
        rightPanel.add(employeeclickhereLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        employeeusernameTextField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        employeeusernameTextField.setPreferredSize(new java.awt.Dimension(490, 42));
        employeeusernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeusernameTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(employeeusernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        adminpasswordLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        adminpasswordLabel.setText("Password");
        rightPanel.add(adminpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        loginLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        loginLabel4.setText("Enter your credentials to proceed");
        rightPanel.add(loginLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        switchLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        switchLabel.setText("Are you an admin?");
        rightPanel.add(switchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, -1));

        closeButton.setBackground(new java.awt.Color(30, 154, 224));
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        rightPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 70, -1));

        employeePasswordField.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        rightPanel.add(employeePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 490, 40));

        adminLoginButton.setBackground(new java.awt.Color(30, 154, 224));
        adminLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginButton.setText("LOGIN NOW");
        adminLoginButton.setBorderPainted(false);
        adminLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        rightPanel.add(adminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 490, 40));

        employeeShowPassword.setText("Showpassword");
        employeeShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeShowPasswordActionPerformed(evt);
            }
        });
        rightPanel.add(employeeShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 840, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
       
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        // TODO add your handling code here:
        
        closeButton.setBackground(new java.awt.Color(204,0,51));
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        // TODO add your handling code here:
        closeButton.setBackground(new java.awt.Color(30,154,224));
    }//GEN-LAST:event_closeButtonMouseExited

    private void employeeclickhereLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeclickhereLabelMouseClicked
        // TODO add your handling code here:
        adminLogin adminlogin = new adminLogin();
        adminlogin.show();
        dispose();
    }//GEN-LAST:event_employeeclickhereLabelMouseClicked

    private void employeeclickhereLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeclickhereLabelMouseEntered
        employeeclickhereLabel.setForeground(new java.awt.Color(172,172,172));
    }//GEN-LAST:event_employeeclickhereLabelMouseEntered

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void employeeclickhereLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeclickhereLabelMouseExited
        employeeclickhereLabel.setForeground(new java.awt.Color(30,154,224));
        
    }//GEN-LAST:event_employeeclickhereLabelMouseExited

    private void employeeShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeShowPasswordActionPerformed
         if (employeeShowPassword.isSelected()) {
      employeePasswordField.setEchoChar((char)0); //password = JPasswordField
   } else {
      employeePasswordField.setEchoChar('*');
   }
    }//GEN-LAST:event_employeeShowPasswordActionPerformed

    private void employeeusernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeusernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeusernameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton adminLoginButton;
    private javax.swing.JLabel adminpasswordLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPasswordField employeePasswordField;
    private javax.swing.JCheckBox employeeShowPassword;
    private javax.swing.JLabel employeeclickhereLabel;
    private javax.swing.JTextField employeeusernameTextField;
    private javax.swing.JPanel leftPannel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel4;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel switchLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
